source: /home/theron/Music/Library
#destination: /run/media/theron/IPOD/Music
destination: /home/theron/Music/Test
threads: 4
formats:
  flac:
    convert_to: ogg
    command: oggenc -q 8 $source -o $destination
  mp3:
    convert_to: mp3
    command: cp $source $destination
  jpg:
    convert_to: jpg
    command: cp $source $destination
